language: node_js
addons:
  code_climate:
    repo_token: 9781c5da8df01dc106ce20a685ef577563db4f4b0dcdf4d5a9132499c945ea8a
after_success:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export VERSION_NUMBER=1.0.$TRAVIS_BUILD_NUMBER
- npm version "$VERSION_NUMBER"
- git push -q https://tarciosaraiva:$GITHUB_API_KEY@github.com/tarciosaraiva/zombied-chai --tags
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info
deploy:
  provider: npm
  email: tarcio@gmail.com
  api_key:
    secure: ZKKKClmOJYAgg3ALK4I6OWegcuUmldr/fQj//Hnwwi7F+eNgUhHoahz9j38rMsZnE38Ofu10wxD/RB9teKQhFrefB5E4R80uioVACv7o1F4T6a80XKtOVGsSJTKw+7KQ7qznqGPnle6C0MI8QGr3N+/l6nyQBfTSHT5u1K7gQK4cFCyeZiETwdxgDI59/nMspL5AYotnlJVlYwkn22cY1a30EOy0a3C+brCsmjfjc/5LLm6EKr2xUaxD3TXWadF3vFHsoiu54nFXI5ZjQvjBhzJTbmy5tEQugjcaU6RdtH7dXfn7d+AFU2XFhp6fwmcUJd8QQFYYXaVGycCZXW5hbVzuicehQPNx4LvO43orqhBh+i+Bmm24mV55VJfo/C4beuCZhgOEe842Jkz2pF3rpwEfC+ZdcK7yB/ciu/JbAiPBpyKQq6Wd6x7USp1XGv9P1jtP2SJ0kHT3YMWJx1SJvPVIYLeCiECXeP/eFU05ctteimKH5CDCcuqHmy8l/jrNzQh600IryzTmYfuUpdYGkvgbLUsU+xBjStty+TkZFrWmOAXL1FZni8RdY1fben6U7/cbrG5lYjAc+//thnn0d+jnix/RGgO+OIxhYnJnv+E3a2rS/yerVFgIik/9eOHw5BOFYb1OlEGnzxxbDYgcZyJh6qMFBFwrydIO2xj/dJE=
  on:
    tags: true
    repo: tarciosaraiva/zombied-chai
